### PR TITLE
Add maintainer doc: a walkthrough of a simple parse

### PR DESCRIPTION
**Pull request by RMJ10**
This is a write-up of what the parser does when it parses a simple piece of XML.  I found tracing the execution like this to be the easiest way to work out what the hell was going on with such a complicated code base.  Hopefully I've done enough to give people a taste of how the parser works, and give them a good idea of what more complicated XML might be subjected to.

### CODE REVIEW

**Comment by hartwork** [comment]
Hi Rhodri,


excellent article, many thanks!


I have a few comments on details:

> the processor that handles the start-up of parsing and allows for an XML prologue to be present

Q quick reminder or a quality external link on what an XML prologue is would be helpful here.


> before palming the rest of the work onto

"to palm sth. off on so." seems advanced English, I needed to look it up. Can you think of a way to keep it but still help non-native readers with understanding? A footnote, a link, ...?

> will try to deduce the answer as it starts to parse.

Something along "from the content to parse, itself" would be a cool hint on the very source

> internal character format. In this example, the internal format is UTF-8

If that full stop was a colon, there was no chance of starting to wonder what that "internal character format" would be.

> 8-bit, including UTF-8, ASCII, Latin-1 and user-defined encodings

I find the "user-defined encodings" bit a bit puzzling there.  There is no example or why that would be the place of integration etc.

> Putting the first two bytes together [..], so we conclude [..]

Was this meant to be
"[If] putting the first two bytes together [..],[] we conclude [..]"
?
Because it seems like with `*encPtr = encodingTable[UTF_16BE_ENC];` would be a case whre bytes are enough. Am I missing something?

> returns the minimum number of bytes required for a single character

Maybe a reminder on how bytes and characters relate, what a character is by our definition or a link would be cool here.

> that we must have finished the prologue

Add "&mdash; because that starts with "<?" &mdash;" or some other hint on the "?" maybe.

> These handler functions effectively implement a state machine for the parser. We start off in prolog0, which turns our token into `XML_ROLE_INSTANCE_START` and transitions to `error`.

Maybe pull that sentence from right _after_ to right _before_ the code excerpt starting function `prolog0`.

>  the UTF-8 into a Unicode codepoint and look up that codepoint in a large bit array

First use of "codepoint"; definition, link, distinction from character or so would be cool.

> this macro turns out to be 0, so for us it would always be invalid.

There is no verbatim `return 0` in the discussed code so a hint on where that 0 comes from would be cool.

> The CHECK_NMSTRT_CASES macro invisibly accepts it and moves the parse pointer on:

Maybe drop the `invisibly` here? I found that rather confusing at first.

Also we had "would always be invalid" a few words earlier, but now things are accepted. The reader could use help with that.

> "We aren't using namespaces"

I think "using namespaces" refers to the input XML (and not say `-DXML_NS`).

> ```
> case BT_GT:
> gt:
> ```

Took me too long to figure that `gt:` is a jump-label.  Could use a sentence to help.  Also, i wonder if we should move the label definition (in the actual Expat code) to zero-indentation or so to make it look less like a magic case label.

> We want to allocate a TAG structure to hold information about our element.

A motivation would be cool to add, e.g. matching opening with closing tags later or something like that.

> and are made available to user-defined handler functions through the `XML_MemMalloc()`, `XML_MemRealloc()` and `XML_MemFree()` functions. 

Let's put that in braces to communicate that it's not common/core part of the API and /while useful to know) not the most important to remember, okay?

> "solidus", the proper technical name for a slash that no one ever uses

😄 Nevermind 😄

> to check that it hasn't closed more tags than it opened. This could happen, for example if an overly-optimistic general entity expanded to an end tag.

That's a great reminder on what structure this document will make an XML parser serve to the user:
```
<?xml version="1.0"?>
<!DOCTYPE foodoc [
    <!ENTITY foo "<b><c>text</c></b>">
]>
<a>&foo;</a>
```
Can we add a link or embed an example like that somewhere?

>  realises that it has closed the last open tag, and calls `epilogProcessor()`.

Please add a link or summary of what an XML epilogue is.


PS: The pull request says it originates from `RMJ10:master`. Working on branch `master` in a fork will be a workflow problem at some point, so keep that in mind for the next PR.

Best


Sebastian

**Comment by RMJ10** [comment]
I've incorporated your comments and tidied up a few things in commit 89aae950ac3c8ba56996ea054242c173001f136b  Due to utter incompetence on my part with git, it's on RMJ10:master again.  I thought I'd moved to a new branch, but apparently I hadn't.

Footnotes turn out to be tedious to do in Markdown.  Not to worry, I've written enough raw HTML in the past that I'm OK with that.

**Comment by hartwork** [comment]
I have applied you post-review changes now, adding [a tiny change on top](https://github.com/libexpat/libexpat.github.io/commit/ed45ff4ceabf56223bb9c6dce86fab10d37d04f6) that I considered non-controversial. Two comments:

> an integer in the range 0&ndash;1114111 (0x10ffff in hexadecimal), or rather 0&ndash;65535 (0xffff in hex) given that it comes from a three-byte UTF-8

Was "0&ndash;65535" meant to be "2048&ndash;65535" (2048=U+0800)? Because we seem ti only look at three-byte units here.

> _Alice in Wonderland_ by Lewis Carroll.  If you needed this footnote, I disown you.

I didn't need the footnote myself but I feel that `I disown you` is a bit too strong. If you can think of something less hard, I would appreciate it. Just my two cents.

**Comment by RMJ10** [comment]
Valid points.  I've fixed the ranges and mildened my humour re Lewis Carroll in commit 2337a289be224aa64ab2b1b24e5a14fd040882cf

**Comment by hartwork** [comment]
Applied, thank you.

**Pull request merged**
