### PR TITLE
Hash tables

### PR DESCRIPTION
**Pull request by RMJ10**
Created an article about the hash tables that Expat uses internally.

### CODE REVIEW

**Comment by RMJ10** [comment]
Gah.  Sorry, the update of walkthrough1.md should have gone into its own pull request.

**Comment by kwaclaw** [comment]
Very nice article.

Nice to see that the double hashing is still there after the recent changes
(I got this from your article as I did not have time to go trhough the
source code).

Karl

**Comment by hartwork** [comment]
Hi Rhodri,


the hash tables part is merged now.  I [fixed two broken links](https://github.com/libexpat/libexpat.github.io/commit/ee3bef4a2685d4ce421be0c95b6e93e9508af5a2) myself.  below you find my review.


> (or dictionary as they are sometimes called)

I would argue, that a dictionary is a high level structure that can be *built* from a hash table (or a balanced binary tree).  Please separate them more clearly and mention array here please.  We can add a link to an in-depth article on Hash tables as well, for curios readers.


> converted into an index into the table

The reader does not know that we have an array here yet, so "index into the table" is hard to really understand, I suppose.


> [..] Elements and element definitions [..]
> [..] general entities [..]
> [..] parameter entities [..]

Those could use a definition / explanation and/or links.  Only "namespace prefixes" seems trivial to me but maybe not even that one.

> If you recall from the walkthrough

Please add a link and the word "previous" or so.

> As the comment says

May add "in-code" or so to make clear what comment you refer to.


> something that can be done quickly and easily since we made our table size a power of two

Please mention "bitwise and" here and mention that `table->size - 1` is a row of ones, e.g. 0b111111 for initial power of 6.

> takes the next `table->power - 2` bits

I tried to verify that but it seems the `power - 1` shift results in a one-bit overlap with the initial index bits.  In detail, let's take this made up data:

```
mask = 0b111111
power = 6 (matching mask)
hash = 0b11111111111111111111111111111111 (32 ones, to make things stand out)
```
Now let's add pieces of the formular as we go:

* `hash & ~mask` makes `0b11111111111111111111111111000000` (six bits turned to zero)
* `(hash & ~mask) >> (power-1)` makes `0b111111111111111111111111110` (notice that last zero)
* `((hash & ~mask) >> (power-1)) & (mask >> 2)` makes `0b1110`

So it looks closer to `table->power - 3` bits to me (but not exactly due to the overlap).
Did I miss something?  Is the overlap a bug?

Also, if we do double hashing that should be mentioned and linked: https://en.wikipedia.org/wiki/Double_hashing

> co-prime

Please link https://en.wikipedia.org/wiki/Coprime_integers

> "Eventually,"

Is the comma be suppose in the quote with English?  (Not in German)

>  so we don't want to do it too often during a parse!

.. hence the exponential growth pattern.

> This looks exactly like the hash-mask-and-step routine we just saw, mostly because it is exactly the same routine

We should consider extracting a (static) function to resolve that code duplication.

> should lead us quickly to an empty slot

Can we drop "quickly"?  (think billion laughs attack)

> Simples. ^3

I went to that website, don't see anything matching "simples" there.  Was that an ad and they changed it?

> contortions

is advanced English.  Add footnote?


> That's almost everything you need to know about hash tables

Let's limit that to the ones in Expat (because there is quite more, else).

> If you reset a parser (with XML_ParserReset()) to clear it for re-use, this does not fully delete the parser's hash tables.

That's something we need to talk about in detail.  Let's take that to phone.

Best



Sebastian

**Comment by kwaclaw** [comment]
Regarding the wikipedia link to double hashing:
We do double hashing without doing double hashing. We simply use the
left-over bits (the ones not used for indexing into a bucket) to get a
second hash value for free. This is not quite the same as explicit double
hashing.

Karl

**Comment by RMJ10** [comment]
Revisions pushed.  I have a few comments on your comments:

> So it looks closer to table->power - 3 bits to me (but not exactly due to the overlap).
> Did I miss something? Is the overlap a bug?

No, you didn't miss something, I did.  The overlap must be intentional because `PROBE_STEP()` always sets that least significant bit to 1, ensuring the step will always be co-prime with the table size.

> Also, if we do double hashing that should be mentioned and linked

I agree with @kwaclaw; I don't think this is double hashing as such, just making efficient use of the hash bits we have.

>>  This looks exactly like the hash-mask-and-step routine we just saw, mostly because it is exactly the same routine

> We should consider extracting a (static) function to resolve that code duplication.

I suspect this was originally duplicated to avoid the overhead of a function call.  After all, `lookup()` is one of the most frequently called functions in the parser.  I wouldn't want to change it without doing some careful benchmarks.

>>  Simples. ^3

> I went to that website, don't see anything matching "simples" there. Was that an ad and they changed it?

I switched to the Wikipedia article instead, which mentions the catchphrase in the summary.  Sorry, "Simples!" was such a ubiquitous phrase when the meerkat adverts first started that it didn't occur to me that it might not be used at the moment.

**Comment by hartwork** [comment]
> Revisions pushed

Applied, thanks.

> I suspect this was originally duplicated to avoid the overhead of a function call.  After all, `lookup()` is one of the most frequently called functions in the parser.  I wouldn't want to change it without doing some careful benchmarks.

With `static` and optimization enabled a decent compiler should inline it for us.

**Pull request closed without merging**
