### PR TITLE
Subversion -> Apache Subversion

### PR DESCRIPTION
**Pull request by gstein**
It became an official Apache project in February 2010.

### CODE REVIEW

**Review by hartwork — CHANGES_REQUESTED** [review]
Hi @gstein, this HTML is generated from file `content/pages/users.md` using python-based static site generator Pelican. Could you revert the change, edit that file, and run `make sync` to generate a second commit getting the HTML back in sync? That would be perfect. Thanks in advance!

**Comment by gstein** [comment]
You bet, I can definitely do that. I looked in content/pages/ and didn't find a docs/, so looked around for a "docs/users.*" and only saw the .html ... I'll get this PR all fixed up.

fwiw, I'm super familiar with Pelican. I wrote a plugin for it, to enable GFM rather than the builtin markdown. See https://github.com/apache/infrastructure-pelican/blob/master/plugins/gfm.py and surrounding bits.

**Comment by hartwork** [comment]
@gstein the github flavored markdown one may be of interest to others. Maybe it's worth a package on PyPI.
Did you close the pull request with the intention to open  new one? The PR and branch can be reused using force push. It leaves fewer PR zombies, if you like.

**Comment by hartwork** [comment]
@gstein okay, I understand. If you ever need help with a Git problem, please feel free to reach out.
Regarding GFM, I moved from Pelican to Nikola for my two other sites and so Expat is the only Pelican, and that's not changing much recently. So no need to do it for me personally, but thanks for the offer!

**Comment by hartwork** [comment]
Superseded by #19

**Pull request closed without merging**
